### ISSUE TITLE
Gene search errors for hg19

### ISSUE THREAD

**Issue by colombelli** [bioinfo-hcpa/pynoma#2]
## Description

A user reported having issues with `geneSearch` for h19. We don't have much more information than that and should try to replicate the error and fix it.

## To Reproduce

No information provided.

## Expected behavior

Gene search functionality should return error-free expected results independently of the chosen genome of reference.

## Priority

High. This is one of the core functionalities and should not be left inoperable.

## Additional details

None provided.

**Comment by colombelli** [comment]
When trying out with `TMPRSS2` or `ADAM17`, after a few tries, I got a JSON decoding error. But it happens at random and seems to be related to unstable gnmoAD responses.

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/home/colombelli/miniconda3/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/colombelli/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/colombelli/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/colombelli/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/colombelli/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_74918/1107241383.py", line 2, in <module>
    gs = GeneSearch('hg19', "TMPRSS2")
  File "/home/colombelli/Programming/pynoma/pynoma/Search.py", line 157, in __init__
    gene: The gene name to search for.
  File "/home/colombelli/Programming/pynoma/pynoma/Search.py", line 166, in get_ensembl_id
  File "/home/colombelli/Programming/pynoma/pynoma/Search.py", line 48, in request_gnomad
    return response.json()
  File "/home/colombelli/miniconda3/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>429</title>429 Too Many Requests: 0
```

**Comment by colombelli** [comment]
Given the <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>429</title>429 Too Many Requests: 0
I'll try to identify the error and retry a few times, logging that this is happening.

**Comment by colombelli** [comment]
I've experimented a bit, and it seems like the waiting for 3, 5 or 10 seconds is too little; waiting for 20 is enough, it addressed the issue.
